// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzyarmpiwlbhdjnaivyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6eWFybXBpd2xiaGRqbmFpdnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjM5MTcsImV4cCI6MjA2NzYzOTkxN30.wuGxQdRbrd8dqaK21gZRq6V2NVyJq8ghE5DWfcUMyKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});